#!/system/bin/sh
# powercfg template by cjybyjk & yc9559
# License: GPL V3

project_name="template"
prj_ver="(prj_ver)"
project_author="cjybyjk"
soc_model=""
generate_date=""

is_big_little=true

C0_GOVERNOR_DIR="/sys/devices/system/cpu/cluster_0/cpufreq/interactive"
C1_GOVERNOR_DIR="/sys/devices/system/cpu/cluster_1/cpufreq/interactive"
C0_CPUFREQ_DIR="/sys/devices/system/cpu/cluster_0/cpufreq"
C1_CPUFREQ_DIR="/sys/devices/system/cpu/cluster_1/cpufreq"

if ! $is_big_little ; then
	C0_GOVERNOR_DIR="/sys/devices/system/cpu/cpufreq/interactive"
fi

# $1:timer_rate $2:value
function set_param_little() 
{
	echo ${2} > ${C0_GOVERNOR_DIR}/${1}
}

function set_param_big() 
{
	echo ${2} > ${C1_GOVERNOR_DIR}/${1}
}

function set_param_all() 
{
	set_param_little ${1} "${2}"
	$is_big_little && set_param_big ${1} "${2}"
}

function set_param_HMP()
{
	echo ${2} > /proc/sys/kernel/${1}
}

# $1:timer_rate
function print_param() 
{
	if $is_big_little ; then
		print_value "LITTLE: ${1}" ${C0_GOVERNOR_DIR}/${1}
		print_value "big: ${1}" ${C1_GOVERNOR_DIR}/${1}
	else
		print_value "${1}" ${C0_GOVERNOR_DIR}/${1}
	fi
}

function wake_up_clusters()
{
	echo "waiting for cluster_0 and cluster_1 online"
	until [ "`cat /sys/devices/system/cpu/cluster_0/online`" = "1" ] &&  [ "`cat /sys/devices/system/cpu/cluster_1/online`" = "1" ]
	do
		for coreOnline in /sys/devices/system/cpu/cpu*/online
		do
			[ "0" = "`cat $coreOnline`" ] && continue
			core=(${coreOnline//\// })
			if [[ "cluster_1" != "${core[4]}" ]] && [[ "cluster_0" != "${core[4]}" ]]; then
				echo "shutting down ${core[4]}"
				set_value 0 $coreOnline
			fi
		done
		set_value 1 /sys/devices/system/cpu/cluster_0/online
		set_value 1 /sys/devices/system/cpu/cluster_1/online
	done
}

function before_modify()
{
	lock_value "interactive" ${C0_CPUFREQ_DIR}/scaling_governor
	chown 0.0 ${C0_GOVERNOR_DIR}/*
	chmod 0666 ${C0_GOVERNOR_DIR}/*
	if $is_big_little ; then
		lock_value "interactive" ${C1_CPUFREQ_DIR}/scaling_governor
		chown 0.0 ${C1_GOVERNOR_DIR}/*
		chmod 0666 ${C1_GOVERNOR_DIR}/*
	fi
	# before_modify_params
}

function after_modify()
{
	chmod 0444 ${C0_GOVERNOR_DIR}/*
	$is_big_little && chmod 0444 ${C1_GOVERNOR_DIR}/*
	# after_modify_params
	verify_param
}

# $1:value $2:file path
function set_value() 
{
	if [ -f $2 ]; then
		echo $1 > $2
	fi
}

# $1:value $2:file path
function lock_value()
{
	if [ -f $2 ]; then
		# chown 0.0 $2
		chmod 0666 $2
		echo $1 > $2
		chmod 0444 $2
	fi                                                  
}

# $1:display-name $2:file path
function print_value() 
{
	if [ -f $2 ]; then
		echo $1
		cat $2
	fi
}

function verify_param() 
{
	expected_target=${C0_GOVERNOR_DIR}/target_loads
	if [ "$action" = "powersave" ]; then
		expected_value="(powersave_tload)"
	elif [ "$action" = "balance" ]; then
		expected_value="(balance_tload)"
	elif [ "$action" = "performance" ]; then
		expected_value="(performance_tload)"
	elif [ "$action" = "fast" ]; then
		expected_value="(fast_tload)"
	fi
	if [ "`cat ${expected_target}`" = "${expected_value}" ]; then
		echo "${action} OK"
	elif [ "${expected_value}" = "(${action}_tload)" ]; then
		echo "${action} not included"
	else
		echo "${action} FAIL"
	fi
}

function get_mode()
{
    expected_target=${C0_GOVERNOR_DIR}/target_loads
	case "`cat ${expected_target}`" in
		"(powersave_tload)" ) echo "powersave OK" ;;
		"(balance_tload)" ) echo "balance OK" ;;
		"(performance_tload)" ) echo "performance OK" ;;
		"(fast_tload)" ) echo "fast OK" ;;
	esac
}

# RunOnce
if [ ! -f /dev/perf_runonce ]; then
	# set flag
	touch /dev/perf_runonce
	
	# HMP_params
	# runonce_params
fi

action=$1
if [ ! -n "$action" ]; then
    action="balance"
fi

$is_big_little && wake_up_clusters

if [ "$action" = "debug" ]; then
	echo "$project_name"
	echo "Version: $prj_ver"
	echo "Author: $project_author"
	echo "Platform: $soc_model"
	echo "Generated at $generate_date"
	echo ""
	print_param above_hispeed_delay
	print_param target_loads
	get_mode
	exit 0
fi

before_modify

if [ "$action" = "powersave" ]; then
	# powersave_params
fi

if [ "$action" = "balance" ]; then
	# balance_params
fi

if [ "$action" = "performance" ]; then
	# performance_params
fi

if [ "$action" = "fast" ]; then
	# fast_params
fi

after_modify

exit 0
