VER="1.2.7"
project_id="(unknown)"
project_name="(未指定项目)"
project_author="(unknown)"
param_allowance_check="true"
text_editor="vim"
powercfg_debug_flag="false"
zip_flashable_outpath="$basepath/flashable"
